version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
    # depends_on: # frontend가 backend에 의존하도록 설정
    #   - backend 

  # backend:
  #   build: ./backend # 백엔드 프로젝트의 Dockerfile이 있는 경로
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/rookiejangter_db?allowPublicKeyRetrieval=true&useSSL=false # MariaDB 컨테이너 이름 사용
  #     SPRING_DATASOURCE_USERNAME: rookiejangter
  #     SPRING_DATASOURCE_PASSWORD: rookiejangter
  #     SPRING_REDIS_HOST: redis
  #     SPRING_REDIS_PORT: 6379
  #   depends_on:
  #     - mariadb
  #     - redis
  #   volumes:
  #     - ./backend/src:/app/src
  #     - ./backend/logs:/app/logs

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: rookiejangter_db
      MARIADB_USER: rookiejangter
      MARIADB_PASSWORD: rookiejangter
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

volumes:
  mariadb_data: