version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - .frontend/src:/app/src  # 소스 코드 폴더 마운트
      - .frontend/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true  # 파일 변경 감지를 위한 설정
  
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped