myprop:
  username: Prod Env

logging:
  level:
    com:
      miniproject:
        joongo: info
    # org:
    #   hibernate:
    #     SQL: DEBUG
    #     type:
    #       descriptor:
    #         sql:
    #           BasicBinder: TRACE

spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/rookiejangter_db
    username: rookiejangter
    password: rookiejangter
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        default_schema: rookiejangter_db # 데이터베이스 이름을 스키마로 사용
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always # always: 항상 실행, embedded: 임베디드 데이터베이스에서만 실행, never: 실행 안 함
      platform: mariadb # 사용할 데이터베이스 플랫폼을 명시 (선택 사항)
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml # 또는 db.changelog-master.xml, db.changelog-master.json
    enabled: true # Liquibase 활성화 여부 (기본값 true)
    # default-schema: my_schema # 특정 스키마에서 작업할 경우 (선택 사항)
    # drop-first: true # 애플리케이션 시작 시 DB 스키마를 먼저 삭제할지 여부 (주의! 개발 단계에서만 사용)
    # liquibase-schema: liquibase # Liquibase 메타데이터 테이블이 생성될 스키마 (기본값은 datasource 스키마)
    # liquibase-tablespace: liquibase_ts # Liquibase 메타데이터 테이블의 테이블스페이스 (선택 사항)


jwt:
  secret: "64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff"