myprop:
  username: Prod Env

logging:
  level:
    com:
      miniproject:
        joongo: info
    # org:
    #   hibernate:
    #     SQL: DEBUG
    #     type:
    #       descriptor:
    #         sql:
    #           BasicBinder: TRACE

spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/rookiejangter_db
    username: rookiejangter
    password: rookiejangter
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect